BASE_TASK_CONFIG_PATH: "configs/vistargetnav_mp3d.yaml"
TRAINER_NAME: "custom_ddppo"
ENV_NAME: "VisTargetNavRLEnv"
SIMULATOR_GPU_ID: 0
TORCH_GPU_ID: 0
VIDEO_OPTION: ["disk", "tensorboard"]
TENSORBOARD_DIR: "logs/ddppo/vistrg_nav_mp3d"
VIDEO_DIR: "data/video_dir/vistrg_nav_mp3d"
TEST_EPISODE_COUNT: 2184
EVAL_CKPT_PATH_DIR: "data/new_checkpoints/vistrg_nav_mp3d"
NUM_PROCESSES: 1
SENSORS: ["DEPTH_SENSOR", "RGB_SENSOR"]
CHECKPOINT_FOLDER: "data/new_checkpoints/vistrg_nav_mp3d"
NUM_UPDATES: 100000000
LOG_INTERVAL: 10
CHECKPOINT_INTERVAL: 200
VIS_INTERVAL: 200
RL:
  SUCCESS_REWARD: 2.5
  SUCESS_MEASURE: 'SUCCESS'
  PPO:
    # ppo params
    clip_param: 0.2
    ppo_epoch: 2
    num_mini_batch: 1
    value_loss_coef: 0.5
    entropy_coef: 0.01
    lr: 1e-5
    eps: 1e-5
    max_grad_norm: 0.2
    num_steps: 128
    use_gae: True
    gamma: 0.99
    tau: 0.95
    use_linear_clip_decay: False
    use_linear_lr_decay: False
    reward_window_size: 10

    use_normalized_advantage: False

    hidden_size: 512

  DDPPO:
    sync_frac: 0.6
    # The PyTorch distributed backend to use
    distrib_backend: NCCL
    # Visual encoder backbone
    pretrained_weights: data/new_checkpoints/vistrg_nav_mp3d/ckpt.124.pth
    # Initialize with pretrained weights
    pretrained: True
    # Initialize just the visual encoder backbone with pretrained weights
    pretrained_encoder: False
    # Whether or not the visual encoder backbone will be trained.
    train_encoder: True
    # Whether or not to reset the critic linear layer
    reset_critic: False

    # Model parameters
    backbone: resnet50
    rnn_type: LSTM
    num_recurrent_layers: 2
